accordion/urls.py
from django.urls import path

from . import views

app_name = 'accordion'

urlpatterns = [
    path('', views.accordion, name='accordion'),
]

account/urls.py
from django.urls import path
from .views import UserRegisterView
from . import views


urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),  
    path('welcome/', views.welcome , name='welcome')  
]

classes/urls.py
from django.urls import path

from . import views
from .views import ClassesView, ClassesDetailView, ClassesDeleteView

app_name = 'classes'

urlpatterns = [
    path('', ClassesView.as_view(), name='list'),
    path('detail/<int:pk>', ClassesDetailView.as_view(), name='classes-detail'),
    path('delete/<int:pk>', ClassesDeleteView.as_view(), name='classes-delete'),
    path('add/', views.add, name='add'),
]

events/urls.py
from django.urls import path

from . import views
from .views import EventsView, AddEventView, AddMemberView

app_name = 'events'

urlpatterns = [
    path('', EventsView.as_view(), name='list'),
    path('add-member/', AddMemberView.as_view(), name='add-member'),
    path('add-event/', AddEventView.as_view(), name='add-event'),
    # path('add-event/POST', views.test, name = 'test'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('album', views.album, name='album'),
    path('oldIndex', views.oldIndex, name='oldIndex'),
]

samuelsharon/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('classes/', include('classes.urls')),
    path('events/', include ('events.urls')),
    path('accordion/', include('accordion.urls')),
    path('search/', include('search.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),
]

search/urls.py
from django.urls import path

from . import views

app_name = 'search'

urlpatterns = [
    path('', views.page, name='page'),
    path('search', views.search, name='search'),
]

accordion/models.py
from django.db import models

# Create your models here.

account/models.py
from django.db import models

# Create your models here.

classes/models.py
from django.db import models

# Create your models here.
class Classes(models.Model):
    matkul = models.CharField(max_length=45)
    dosen = models.CharField(max_length=75)
    sks = models.CharField(max_length=2)
    desc = models.TextField()
    semester = models.CharField(max_length=45)
    ruang = models.CharField(max_length=45)

events/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Events (models.Model):
    event = models.CharField(max_length=45)

    def __str__(self):
        return self.event

    def get_absolute_url(self):
        return reverse('events:list')


class Members (models.Model):
    member = models.CharField(max_length=45)
    event = models.ForeignKey(Events, on_delete=models.CASCADE)

    def __str__(self):
        return self.member

    def get_absolute_url(self):
        return reverse('events:list')

home/models.py
from django.db import models

# Create your models here.

search/models.py
from django.db import models

# Create your models here.

classes/forms.py
from django import forms

from .models import Classes

class ClassesForm(forms.ModelForm):
    class Meta:
        model = Classes
        fields = [
            'matkul',
            'dosen',
            'sks',
            'desc',
            'semester',
            'ruang',
        ]
        widgets = {
            'matkul': forms.TextInput(attrs={'class': 'form-control'}),
            'dosen': forms.TextInput(attrs={'class': 'form-control'}),
            'sks': forms.TextInput(attrs={'class': 'form-control'}),
            'desc': forms.Textarea(attrs={'class': 'form-control'}),
            'semester': forms.TextInput(attrs={'class': 'form-control'}),
            'ruang': forms.TextInput(attrs={'class': 'form-control'}),
        }

accordion/views.py
from django.shortcuts import render

# Create your views here.
def accordion(request):
    return render(request, 'accordion/jquery-accordion.html')

account/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

# Create your views here.
class UserRegisterView(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')

def welcome(request):
    return render(request, 'registration/welcome.html')

classes/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, DeleteView
from .forms import ClassesForm
from .models import Classes
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# Create your views here.

class ClassesView(ListView):
    model = Classes
    template_name = 'classes/list.html'

class ClassesDetailView(DetailView):
    model = Classes
    template_name = 'classes/detail.html'

@method_decorator(login_required(login_url='login'), name='dispatch')
class ClassesDeleteView(DeleteView):
    model = Classes
    template_name = 'classes/delete.html'
    success_url = reverse_lazy('classes:list')

@login_required(login_url='login')
def add(request):
    form = ClassesForm(request.POST or None)
    if form.is_valid():
        form.save()
    context = {
        'form': form
    }
    return render(request, 'classes/add.html', context)

events/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView
from .models import Events, Members


# Create your views here.
class EventsView(ListView):
    context_object_name = 'list'
    template_name = 'events/events.html'
    queryset = Events.objects.all()

    def get_context_data(self, **kwargs):
        context = super(EventsView, self).get_context_data(**kwargs)
        context['members'] = Members.objects.all()
        return context


class AddEventView(CreateView):
    model = Events
    template_name = 'events/add-event.html'
    fields = '__all__'

class AddMemberView(CreateView):
    model = Members
    template_name = 'events/add-member.html'
    fields = '__all__'

# def test(request):
#     return render(request, 'events/test.html')

home/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'home/index.html')

def album(request):
    return render(request, 'home/album.html')

def oldIndex(request):
    return render(request, 'home/oldIndex.html')

search/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
import requests
import json

# Create your views here.
def page(request):
    return render(request, 'search/search.html')

def search(request):
    query = request.GET['search_key']
    search_url = 'https://www.googleapis.com/books/v1/volumes?q=' + query +'&maxResults=36'
    response = requests.get(search_url)

    json_result = json.loads(response.content)
    return JsonResponse(json_result, safe = False)

accordion/templates/accordion/accordion.html
<!-- <!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
.accordion {
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 100%;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
  transition: 0.4s;
}

.active, .accordion:hover {
  background-color: #ccc; 
}

.panel {
  padding: 0 18px;
  display: none;
  background-color: white;
  overflow: hidden;
}
</style>
</head>
<body> -->
{% extends "base.html" %}

{% block content %}
<h2>Accordion</h2>


<button class="accordion" id="test1">toyota</button>
<div class="panel">
  <p id="test">saab</p>
</div>

<button class="accordion" id="test2">mustang</button>
<div class="panel">
  <p id="test3">volvo</p>
</div>

<button class="accordion" id="test4">hellcat</button>
<div class="panel">
  <p id="test5">bmw</p>
</div>

<button onclick="swap1()">switch down</button>
<button onclick="swap2()">switch down</button>
<button onclick="swap3()">switch down</button>

<button onclick="swap3()">switch up</button>
<button onclick="swap1()">switch up</button>
<button onclick="swap2()">switch up</button>

<script>
function swap1() {
var a = cars[0]
cars[0] = cars[1];
var b = mobil[0]
mobil[0] = mobil[1];

cars[1] = a;
mobil[1] = b;

document.getElementById('test').innerHTML = cars[0]
document.getElementById('test1').innerHTML = mobil[0]

document.getElementById('test3').innerHTML = cars[1]
document.getElementById('test2').innerHTML = mobil[1]
}


function swap2() {
var a = cars[1]
cars[1] = cars[2];
var b = mobil[1]
mobil[1] = mobil[2];

cars[2] = a;
mobil[2] = b;

document.getElementById('test3').innerHTML = cars[1]
document.getElementById('test2').innerHTML = mobil[1]

document.getElementById('test5').innerHTML = cars[2]
document.getElementById('test4').innerHTML = mobil[2]
}


function swap3() {
var a = cars[2]
cars[2] = cars[0];
var b = mobil[2]
mobil[2] = mobil[0];

cars[0] = a;
mobil[0] = b;

document.getElementById('test5').innerHTML = cars[2]
document.getElementById('test4').innerHTML = mobil[2]

document.getElementById('test').innerHTML = cars[0]
document.getElementById('test1').innerHTML = mobil[0]
}

var mobil = ["toyota", "mustang", "hellcat"]
var cars = ["Saab", "Volvo", "BMW"];
var acc = document.getElementsByClassName("accordion");
var i;

for (i = 0; i < acc.length; i++) {
  acc[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var panel = this.nextElementSibling;
    if (panel.style.display === "block") {
      panel.style.display = "none";
    } else {
      panel.style.display = "block";
    }
  });
}

</script>
{% endblock %}

<!-- </body>
</html> -->

accordion/templates/accordion/jquery-accordion.html
{% extends "base.html"%}

{% block content %} 
<div class="dark-background">
<!-- <div class="whitespace-2"></div> -->
<div class="whitespace-5"></div>
<div class="text-center">
  <h1 class="d-none d-md-block title-name-1 color-2">Accordion</h1>
  <h1 class="d-md-none title-name-3 color-2">Accordion</h1>
  <br>
</div>
<div class="rounded" id="accordion" style="width: 400px; margin:auto; border-style: solid; border-color: #021800;background-color: #021800;border-width:25px;">
  <h5 class="color-2 content-2" > <span id="judul0">Aktivitas</span> <span style="float: right;"><button class="updown rounded" onclick="swap(0,1)">▼</button><button class="updown rounded" onclick="swap(3,0)">▲</button></span> </h3> 
  <div class="rounded container color-3 content-3" style="background-color: white;" id="isi0">
    <br><ul><li>Lab SDA AVL Tree</li><li>Profile Web Project</li><li>Studying MIPS Datapath</li></ul><br>
  </div>
  <h5 class="color-2 content-2"> <span id="judul1">Pengalaman Organisasi</span> <span style="float: right;"><button class="updown rounded" onclick="swap(1,2)">▼</button><button class="updown rounded" onclick="swap(0,1)">▲</button></span></h3>
  <div class="rounded container color-3 content-3" style="background-color: white;" id="isi1">
    <br><ul><li>Panitia Buang Anggaran</li><li>Juri lomba makan kerupuk</li><li>Co-Founder Google</li></ul><br>
  </div>
  <h5 class="color-2 content-2"><span id="judul2">Prestasi</span> <span style="float: right;"><button class="updown rounded" onclick="swap(2,3)">▼</button><button class="updown rounded" onclick="swap(1,2)">▲</button></span></h3>
  <div class="rounded container color-3 content-3" style="background-color: white;" id="isi2">
    <br><ul><li>Juara 1 makan angin</li><li>Juara 3 Prokrastinasi</li><li>Juara harapan lulus SD</li><li>Juara 5 Lomba Gambar TK</li></ul><br>
  </div>
  <h5 class="color-2 content-"><span id="judul3">Riwayat Sekolah</span> <span style="float: right;"><button class="updown rounded" onclick="swap(3,0)">▼</button><button class="updown rounded" onclick="swap(2,3)">▲</button></span></h3>
  <div class="rounded container color-3 content-3" style="background-color: white;" id="isi3">
    <br><ul><li>SD Maria Fransiska</li><li>SDK 4 Penabur</li><li>SMPK 5 Penabur</li><li>SMAK 7 Penabur</li></ul><br>
  </div>
</div>
<div class="whitespace-3"></div>
</div>

<script>

    var mobil = [
        "Aktivitas", 
        "Pengalaman Organisasi", 
        "Prestasi", 
        "Riwayat Sekolah",
    ];
    var cars = [
        "<br><ul><li>Lab SDA AVL Tree</li><li>Profile Web Project</li><li>Studying MIPS Datapath</li></ul><br>", 
        "<br><ul><li>Panitia Buang Anggaran</li><li>Juri lomba makan kerupuk</li><li>Co-Founder Google</li></ul><br>", 
        "<br><ul><li>Juara 1 makan angin</li><li>Juara 3 Prokrastinasi</li><li>Juara harapan lulus SD</li><li>Juara 5 Lomba Gambar TK</li></ul><br>", 
        "<br><ul><li>SD Maria Fransiska</li><li>SDK 4 Penabur</li><li>SMPK 5 Penabur</li><li>SMAK 7 Penabur</li></ul><br>",
    ];

    function swap(x,y) {
    var a = cars[x]
    cars[x] = cars[y];
    var b = mobil[x]
    mobil[x] = mobil[y];
    
    cars[y] = a;
    mobil[y] = b;
    
    document.getElementById('isi'+x).innerHTML = cars[x]
    document.getElementById('judul'+x).innerHTML = mobil[x]
    
    document.getElementById('isi'+y).innerHTML = cars[y]
    document.getElementById('judul'+y).innerHTML = mobil[y]
    }
    </script>
{% endblock %}
 
 

classes/templates/classes/add.html
{% extends "base.html" %}
{% block content %}

<div class="container text-center content" style="max-width: 600px;">
    <div class="whitespace-2"></div>
    <div class="text-center">
        <h1 class="title-name-2 color-2">Add Subjects</h1>
        <br>
    </div>
    <form method='POST'> {% csrf_token %}
        {{ form.as_p}}
        <input type='submit' value='save' />
    </form>
    <br>
    <a href="/classes/">Show Me The Result</a>
</div>
<div class="whitespace-1"></div>
{% endblock %}

classes/templates/classes/delete.html
{% extends "base.html" %}
{% block content %}
<div class="container text-center content">
    <div class="whitespace-1"></div>
    <h3>Delete: {{ classes.matkul }}</h3>
    <br><br>
    <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            <strong>Are you sure about that?</strong>
            <br><br>
            <button class="btn btn-secondary">Delete Class</button>
        </form>
    </div>
    <a href="/classes/"><h4>No! Take Me Back!</h4></a>
</div>
<div class="whitespace-1"></div>
<div class="whitespace-4"></div>
{% endblock %}

classes/templates/classes/detail.html
{% extends "base.html" %}
{% block content %}
<div class="whitespace-4"></div>
<div class="content container">
    <h1 class="text-center title-name-2 color-2">{{ classes.matkul }}</h1>
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
              <th scope="col">#</th>
              <th scope="col"></th>
              <th scope="col">Penjelasan</th>
            </tr>
          </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>mata Kuliah</td>
            <td>{{ classes.matkul }}</td>
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>Dosen</td>
            <td>{{ classes.dosen }}</td>
          </tr>
          <tr>
            <th scope="row">3</th>
            <td>Jumlah SKS</td>
            <td>{{ classes.sks }}</td>
          </tr>
         
          <tr>
            <th scope="row">4</th>
            <td>Semester Tahun</td>
            <td>{{ classes.semester }}</td>
          </tr>
          <tr>
            <th scope="row">5</th>
            <td>Ruang Kelas</td>
            <td>{{ classes.ruang }}</td>
          </tr>
          <tr>
            <th scope="row">6</th>
            <td>Deskripsi Mata Kuliah</td>
            <td>{{ classes.desc }}</td>
          </tr>
        </tbody>
      </table>
</div>
<div class="whitespace-1"></div>
{% endblock %}

classes/templates/classes/list.html
{% extends "base.html" %}
{% block content %}
<div>
    <div class="whitespace-4"></div>
    <div class="text-center">
        <h1 class="title-name-2 color-2">These Are the Classes I am Taking</h1>
    </div>
    <div class="whitespace-2"></div>
    <div class="text-center container">

        <table class="table table-striped content">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Subject</th>
                        <th scope="col">Press X to Remove</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in object_list %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a class="color-1" href="{% url 'classes:classes-detail' item.pk %}">{{ item.matkul }}</a></td>
                        <td>
                            <a href="{% url 'classes:classes-delete' item.pk %}"><h3 style="text-align: center; color: red;">X</h3></a>
                        </td>
                    </tr>

                    {% endfor %}
                </tbody>
            </table>
            <br><br>
        <a href="/classes/add"><h1 class="content color-2">Add Class</h1></a>
    </div>
</div>
<div class="whitespace-1"></div>

{% endblock %}

events/templates/events/add-event.html
{% extends 'base.html' %}

{% block content %}
<div class="whitespace-2"></div>
<div class="container text-center">
    <div class="whitespace-1"></div>
    <h1 class="title-name-2">What's the Event</h1>
    <div class="whitespace-2"></div>
    {%if user.is_authenticated%}
        <form method="POST">{%csrf_token%}
            {{form.as_p}}
            <button>Add It!</button>
        </form>
    {%else%}
        <p>To access this you will need to <a href="{% url 'login'%}">Login</a></p>
    {%endif%}
    
    <div class="whitespace-1"></div>
    <div class="whitespace-2"></div>

</div>
{% endblock %}

events/templates/events/add-member.html
{% extends 'base.html' %}

{% block content %}
<div class="whitespace-2"></div>
<div class="container text-center">
    <div class="whitespace-1"></div>
    <h1 class="title-name-2">Write Your Name</h1>
    <div class="whitespace-2"></div>
    {%if user.is_authenticated%}
        <form method="POST">{%csrf_token%}
            {{form.as_p}}
            <button>Add me!</button>
        </form>
    {%else%}
        <p>To access this you will need to <a href="{% url 'login'%}">Login</a></p>
    {%endif%}
    
    <div class="whitespace-1"></div>
    <div class="whitespace-2"></div>

</div>
{% endblock %}

events/templates/events/events.html
{% extends "base.html" %}
{% block content %}
<div class="container text-center">
    <div class="whitespace-2"></div>
    <div class="whitespace-2"></div>
    <div class="whitespace-2"></div>
    <h1 class="title-name-1">Upcoming Events</h1>
    <div class="whitespace-2"></div>
    <div class="whitespace-2"></div>
    <div class="row color-2">
        {% for event in list %}
        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
            <div class="album dark-background rounded card" style="min-height: 200px;">
                <p class="content" style="text-transform: uppercase;background-color: white;">{{event.event}}</p>

                {% for member in members %}

                {% if member.event == event %}
                <p class="content" style="color: whitesmoke;">{{member.member}}</p>
                {% endif %}

                {% endfor %}
            </div>
        </div>
        {% endfor %}

    </div>
    <div class="whitespace-2"></div>
    <div class="btn btn-warning">
        <a href="/events/add-event/">
            <h1 class="title-prefix" style="color: white;">Add Event</h1>
        </a>
    </div>
    <div class="btn btn-warning">
        <a href="/events/add-member/">
            <h1 class="title-prefix" style="color: white;">Add Member</h1>
        </a>
    </div>
    <div class="whitespace-1"></div>
</div>
{% endblock %}

events/templates/events/test.html
test

home/templates/home/album.html
{% extends "base.html" %}

                    {% block sidebar-content %}
                    <a class="color-2" href="#me"> <h1 class="content-2">My photos</h1> </a>
                    <a class="color-2" href="#friends"> <h1 class="content-2">Friends</h1> </a>
                    <a class="color-2" href="#family"> <h1 class="content-2">Family</h1> </a>
                    <a class="color-2" href="#random"> <h1 class="content-2">Random^2</h1> </a>
                    {% endblock %}

                    {% block content %}
            <div style="background-color: #000D00;">
                <div class="whitespace-2"></div>
                <div class="whitespace-2"></div>
                <div class="text-center">
                    <h1 class="title-name-2 color-2" id="home">Random Photos on My Computer</h1>
                </div>
                <div class="whitespace-2"></div>
                <div class="row col-10 offset-1" >
                    <div id="me" class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/1.JPG" alt=""></div>
                    <div id="friends" class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/2.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/3.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/4.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/5.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/6.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/7.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/9.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/10.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/11.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/12.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/13.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/14.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/15.JPG" alt=""></div>
                    <div id="family" class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/16.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/17.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/18.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/19.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/20.JPG" alt=""></div>
                    <div id="random" class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/21.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/22.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/23.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/24.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/25.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/26.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/27.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/28.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/29.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/30.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/31.JPG" alt=""></div>
                    <div class="col-xl-3 col-lg-4 col-md-6 col-sm-12">
                    <img class="album" src="static/images/Album/32.JPG" alt=""></div>
                </div>
                <div class="whitespace-2"></div>
                <div class="whitespace-2"></div>
                <div class="whitespace-2"></div>
                <div style="background-color: white;">
                        <div class="whitespace-4"></div>
                        <div class="text-center">
                            <a href="#home">
                                <img src="static/images/arrow-up-01-512.webp" style="width: 100px;" alt="">
                                <p class="content color-2">Get Back to top!</p>
                            </a>

                            <div class="whitespace-2"></div>
                            <p class="content-2 color-2">or</p>
                            <div class="whitespace-2"></div>

                            <a href="index">
                                <p class="content color-2">Go back to main page</p>
                                <img src="static/images/arrow-left.png" style="width: 100px;" alt="">
                            </a>
                        </div>
                        <div class="whitespace-4"></div>
                    </div>
            </div>
                {% endblock %}

home/templates/home/oldIndex.html
{% extends "base.html" %}


  {% block content %}
  <div class="col-md-3 d-none d-md-block picture1" style="background-color: black; height: 100%; position: fixed;">

    <div>
      <img src="static/images/Headshot.jpg" alt="Samuel Sharon" style="width: 90%; position: absolute; top: 50%; 
      transform: translateY(-50%);" class="mx-auto d-block rounded-circle">

    </div>
  </div>
  <div class="col-xl-7 col-lg-8 col-md-8 col-12 float-right">

    <div style="height: 200px"></div>

    <h1>ABOUT</h1>

    <h1 style="font-size: 2cm; font-weight: bolder; font-family: Arial, Helvetica, sans-serif; color: #800000;" ;>SAMUEL
      SHARON </h1>
    <h4>STUDENT - SAMUELSHARON.WORK@GMAIL.COM </h4>
    <br><br>
    <h4 style="max-width: 30cm;">I am an 18 year old currently enrolled in university studying computer science. My first 
      ever “coding” expirience was when i followed an html course near the end of high school.  
      Ever since I began studying in university i have been wondering what my true passion is but i have not 
      found it as of yet. Though I have been intrested in some roles such as web development. </h4>
    <br>
    <h6>Universitas Indonesia - Fakultas Ilmu Komputer 2019 - 1906400204</h6>

    <div style="height:200px"></div>

    <div class="row">
      <div class="col-md-4">
        <h2>Previous Education</h2>
        <h5>SD Maria Fransiska <small>2007-2010</small></h5>
        <h5>SDK4 BPK PENABUR <small>2010-2013</small></h5>
        <h5>SMPK5 BPK PENABUR <small>2013-2016</small></h5>
        <h5>SMAK7 BPK PENABUR <small>2016-2019</small></h5>
      </div>
      <div class="col-md-4">
        <h2>Social Media</h2>
        <h5>Twitter: <small>@samuelsharon10</small></h5>
        <h5>Line: <small>samuel_sidabutar</small></h5>
        <h5>Discord: <small>HANS#7252</small></h5>
        <h5>Ig: <small>totallynotsam_</small></h5>



      {% endblock %}